version: '1.0'
services:
  caddy:
    image: caddy:2
    user: root  # 指定root用户执行，避免premission denied
    restart: always
    container_name: caddy  # 指定容器名称
    ports: # 只有Caddy对外暴露端口
      - 80:80
      - 443:443
      - 9980:9980
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z  # 给所有 volume 后面加 :Z，让 Podman 自动设置 SELinux 标签：
      - ./caddy_data:/data:Z
    networks:
      - caddy_network

  nc_db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    container_name: nc_db  # 指定容器名称
    volumes:
      - ./db_data:/var/lib/mysql:Z
    networks:
      - nc_network
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud

  nc_redis:
    image: redis:alpine
    container_name: nc_redis  # 指定容器名称
    restart: always
    networks:
      - nc_network

  nc:
    image: nextcloud:apache
    user: root
    restart: always
    volumes:
      - ./nc_data:/var/www/html:Z
    hostname: opencodething.top
    container_name: nextcloud  # 指定容器名称
    environment:
      - REDIS_HOST=nc_redis
      - MYSQL_HOST=nc_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_TRUSTED_DOMAINS='opencodething.top' # 自己的域名
    depends_on:
      - nc_db
      - nc_redis
    networks:
    - caddy_network
    - nc_network

  nc_cron:
    image: nextcloud:apache
    container_name: nc_cron  # 指定容器名称
    restart: always
    volumes:
      - ./nc_data:/var/www/html:Z
    entrypoint: /cron.sh
    depends_on:
      - nc_db
      - nc_redis
    networks:
      - nc_network

  lab:
    image: quay.io/jupyter/base-notebook
    user: root
    volumes:
      - ./lab_data:/home/jovyan/work:Z
    restart: always
    container_name: lab  # 指定容器名称
    networks:
      - caddy_network

  ql:
    image: whyour/qinglong:latest
    user: root
    volumes:
      - ./ql_data:/ql/data:Z
    restart: always
    container_name: ql  # 指定容器名称
    networks:
      - caddy_network

  wp_db:
    image: mariadb:10.5
    user: root
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./wp_db_data:/var/lib/mysql:Z
    restart: always
    container_name: wp_db  # 指定容器名称
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
     - wp_network

  wp:
    image: wordpress:latest
    user: root
    volumes:
     - ./wp_data:/var/www/html:Z
    restart: always
    container_name: wordpress  # 指定容器名称
    environment:
      - WORDPRESS_DB_HOST=wp_db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - wp_db
    networks:
     - wp_network
     - caddy_network
  chat_bot:
    image: chatgpt-on-wechat
    user: root
    env_file:
     - chat.env:Z
    restart: always
    container_name: chat_bot # 容器名

  v2ray:
    build:
      context: ./
      dockerfile: V2rayDockerfile
    restart: always
    user: root
    image: my/v2ray:latest
    container_name: v2ray
    ports:
      - 9527:9527
      - 9528:9528
      - 9529:9529
    volumes:
      - ./conf:/etc/v2ray:Z
      - ./logs:/var/log/v2ray:Z

networks:  # 新增部分：定义所有自定义网络
  caddy_network:
    driver: bridge
  nc_network:
    driver: bridge
  wp_network:
    driver: bridge