version: '1.0'
services:
  caddy:
    image: caddy:2
    restart: always
    container_name: caddy  # 指定容器名称
    ports:
      - 80:80
      - 443:443
      - 9980:9980
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
    networks:
      - caddy_network

  nc_db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    container_name: nc_db  # 指定容器名称
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - nc_network
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud

  nc_redis:
    image: redis:alpine
    container_name: nc_redis  # 指定容器名称
    restart: always
    networks:
      - nc_network

  nc:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nc_data:/var/www/html
    hostname: opencodething.top
    container_name: nextcloud  # 指定容器名称
    environment:
      - REDIS_HOST=nc_redis
      - MYSQL_HOST=nc_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_TRUSTED_DOMAINS='opencodething.top'
    depends_on:
      - nc_db
      - nc_redis
    networks:
    - caddy_network
    - nc_network

  nc_cron:
    image: nextcloud:apache
    container_name: nc_cron  # 指定容器名称
    restart: always
    volumes:
      - ./nc_data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nc_db
      - nc_redis
    networks:
      - nc_network

  lab:
    image: quay.io/jupyter/base-notebook
    volumes:
      - ./lab_data:/home/jovyan/work
    restart: always
    container_name: lab  # 指定容器名称
    networks:
      - caddy_network

  ql:
    image: whyour/qinglong:latest
    volumes:
      - ./ql_data:/ql/data
    restart: always
    container_name: ql  # 指定容器名称
    networks:
      - caddy_network

  wp_db:
    image: mariadb:10.5
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./wp_db_data:/var/lib/mysql
    restart: always
    container_name: wp_db  # 指定容器名称
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
     - wp_network

  wp:
    image: wordpress:latest
    volumes:
     - ./wp_data:/var/www/html
    restart: always
    container_name: wordpress  # 指定容器名称
    depends_on:
      - wp_db
networks:  # 新增部分：定义所有自定义网络
  caddy_network:
    driver: bridge
  nc_network:
    driver: bridge
  wp_network:
    driver: bridge